version: '3'

services:
  slackbot:
    build:
      context: ../slackbot
      dockerfile: ../.devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/workspace
      # - ../slackbot/log:/workspace/slackbot/log
    tty: true
    restart: always

  mysql:
    image: mysql:8.0
    expose:
      - 3306
    env_file:
      - ../.env
    restart: always
